Added sed in test for BOM

diff --git a/.github/workflows/formatting.yml b/.github/workflows/formatting.yml
--- a/.github/workflows/formatting.yml
+++ b/.github/workflows/formatting.yml
@@ -33,18 +33,16 @@ jobs:
 
       - name: Check for UTF-8 BOM
         run: |
-             files=`find . -name '*.mo' -print0 | xargs -0 grep -l $'^\\xEF\\xBB\\xBF'`
-             failed="false"
-             if [ "${files}x" != "x" ]; then
-               echo "Found UTF-8 BOM in"
-               for ff in ${files}; do
-                 echo "$ff"
-               done
-               failed="true"
+             find . -name '*.mo' -print0 | xargs -0 grep -l $'^\\xEF\\xBB\\xBF'
+             for ff in `find . -name '*.mo'`; do
+               sed -i '1s/^\xEF\xBB\xBF//' $ff;
+             done
+             retVal=`git diff --exit-code .`
+             if [ "$retVal" != "0" ]; then
+               echo "Error, found BOM in the following files"
+               git diff .
              fi;
-             if [ "${failed}" == "true" ]; then
-                exit 1
-             fi;
+             exit $retVal
 
       - uses: actions/setup-python@v2
         with:
